import { BookOpen, FolderTree, Plus } from 'lucide-react';
import { createChapterAction, createTextbookAction } from '@/app/actions/math-actions';
import { PageHeader, SectionTitle, StatusPill } from '@/components/mistake-atlas/ui';
import { prisma } from '@/lib/prisma';

export default async function TextbooksPage() {
  const math = await prisma.subject.findUniqueOrThrow({ where: { slug: 'mathematics' } });
  const textbooks = await prisma.textbook.findMany({ where: { subjectId: math.id }, include: { chapters: { orderBy: { sortOrder: 'asc' } }, _count: { select: { questions: true } } }, orderBy: { sortOrder: 'asc' } });
  return <><PageHeader eyebrow="Mathematics · Taxonomy" title="教材与章节" description="数学教材和章节采用树形归类；其他学科以后可以使用相同模型建立自己的章节体系。" /><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><div className="space-y-4">{textbooks.map((book) => <section key={book.id} className="atlas-card p-5"><div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><BookOpen className="size-5" /></div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-slate-900">{book.name}</h2><StatusPill tone="blue">{book._count.questions} 道错题</StatusPill></div><p className="mt-1 text-xs text-slate-400">{book.description || '暂无说明'}</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{book.chapters.map((chapter) => <div key={chapter.id} className="flex items-center gap-2 rounded-lg border border-slate-100 bg-slate-50 px-3 py-2 text-sm text-slate-600"><FolderTree className="size-4 text-slate-400" />{chapter.name}</div>)}</div></section>)}{!textbooks.length ? <div className="atlas-card p-8 text-center text-sm text-slate-400">还没有教材。</div> : null}</div><aside className="space-y-5"><form action={createTextbookAction} className="atlas-card p-5"><SectionTitle title="添加数学教材" /><div className="space-y-4"><label><span className="atlas-label">教材名称 *</span><input name="name" required className="atlas-input" placeholder="例如：张宇 1000 题" /></label><label><span className="atlas-label">说明</span><textarea name="description" className="min-h-20 w-full rounded-lg border border-slate-200 p-3 text-sm" /></label><button className="atlas-button-primary w-full"><Plus className="size-4" />添加教材</button></div></form><form action={createChapterAction} className="atlas-card p-5"><SectionTitle title="添加章节" /><div className="space-y-4"><label><span className="atlas-label">所属教材 *</span><select name="textbookId" required className="atlas-input"><option value="">选择教材</option>{textbooks.map((book) => <option key={book.id} value={book.id}>{book.name}</option>)}</select></label><label><span className="atlas-label">父章节（可选）</span><select name="parentId" className="atlas-input"><option value="">顶级章节</option>{textbooks.flatMap((book) => book.chapters.map((chapter) => <option key={chapter.id} value={chapter.id}>{book.name} / {chapter.name}</option>))}</select></label><label><span className="atlas-label">章节名称 *</span><input name="name" required className="atlas-input" /></label><button className="atlas-button-primary w-full"><Plus className="size-4" />添加章节</button></div></form></aside></div></>;
}
