import Link from 'next/link';
import { BookOpen, FileUp, FolderTree, Pencil, Plus } from 'lucide-react';
import { createChapterAction, createTextbookAction, mergeChapterAction, updateChapterAction, updateTextbookAction } from '@/app/actions/math-actions';
import { DangerSubmit } from '@/components/mistake-atlas/danger-submit';
import { PageHeader, SectionTitle, StatusPill } from '@/components/mistake-atlas/ui';
import { prisma } from '@/lib/prisma';

export default async function TextbooksPage() {
  const math = await prisma.subject.findUniqueOrThrow({ where: { slug: 'mathematics' } });
  const textbooks = await prisma.textbook.findMany({ where: { subjectId: math.id }, include: { chapters: { orderBy: { sortOrder: 'asc' } }, _count: { select: { questions: true } } }, orderBy: { sortOrder: 'asc' } });
  return <>
    <PageHeader eyebrow="Mathematics · Taxonomy" title="教材与章节" description="教材和多级章节可由学习资料 Markdown 自动建立，也可以在本页手动维护。" action={<Link href="/learning-import" className="atlas-button-primary"><FileUp className="size-4" />学习资料导入</Link>} />
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]">
      <div className="space-y-4">{textbooks.map((book) => <section key={book.id} className="atlas-card p-5">
        <div className="flex items-start gap-3"><div className="grid size-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><BookOpen className="size-5" /></div><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-slate-900">{book.name}</h2><StatusPill tone="blue">{book._count.questions} 道错题</StatusPill><StatusPill tone={book.active ? 'green' : 'slate'}>{book.active ? '启用' : '停用'}</StatusPill></div><p className="mt-1 text-xs text-slate-400">{book.description || '暂无说明'}</p></div></div>
        <details className="mt-4 rounded-xl border border-slate-100 bg-slate-50 p-4"><summary className="flex cursor-pointer list-none items-center gap-2 text-xs font-semibold text-slate-600"><Pencil className="size-3.5" />编辑教材</summary><form action={updateTextbookAction.bind(null, book.id)} className="mt-4 grid gap-3 md:grid-cols-2"><input name="name" required defaultValue={book.name} className="atlas-input" /><input name="sortOrder" type="number" defaultValue={book.sortOrder} className="atlas-input" /><textarea name="description" defaultValue={book.description || ''} className="min-h-20 rounded-lg border border-slate-200 p-3 text-sm md:col-span-2" /><label className="flex items-center gap-2 text-xs text-slate-600"><input name="active" type="checkbox" defaultChecked={book.active} />允许后续选择</label><button className="atlas-button-secondary">保存教材</button></form></details>
        <div className="mt-4 space-y-2">{book.chapters.map((chapter) => <details key={chapter.id} className="rounded-lg border border-slate-100 bg-white px-3 py-2"><summary className="flex cursor-pointer list-none items-center gap-2 text-sm text-slate-600"><FolderTree className="size-4 text-slate-400" /><span className="flex-1">{chapter.parentId ? '↳ ' : ''}{chapter.name}</span><StatusPill tone={chapter.active ? 'blue' : 'slate'}>{chapter.active ? '启用' : '停用'}</StatusPill></summary><div className="mt-3 grid gap-4 border-t border-slate-100 pt-3 lg:grid-cols-2"><form action={updateChapterAction.bind(null, chapter.id)} className="grid gap-3"><input name="name" required defaultValue={chapter.name} className="atlas-input" /><input name="sortOrder" type="number" defaultValue={chapter.sortOrder} className="atlas-input" /><select name="parentId" defaultValue={chapter.parentId || ''} className="atlas-input"><option value="">顶级章节</option>{book.chapters.filter((item) => item.id !== chapter.id).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><label className="flex items-center gap-2 text-xs text-slate-600"><input name="active" type="checkbox" defaultChecked={chapter.active} />允许后续选择</label><button className="atlas-button-secondary">保存章节</button></form><form action={mergeChapterAction.bind(null, chapter.id)} className="space-y-3"><select name="targetId" required defaultValue="" className="atlas-input"><option value="">合并到同教材的章节</option>{book.chapters.filter((item) => item.id !== chapter.id && item.active).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><p className="text-[11px] leading-5 text-slate-400">题目、子章节和知识点会迁移；同名知识点会自动合并，当前章节随后停用。</p><DangerSubmit label="确认合并章节" confirmText={`确定将“${chapter.name}”合并到所选目标吗？`} /></form></div></details>)}</div>
      </section>)}{!textbooks.length ? <div className="atlas-card p-8 text-center text-sm text-slate-400">还没有教材。</div> : null}</div>
      <aside className="space-y-5"><form action={createTextbookAction} className="atlas-card p-5"><SectionTitle title="添加数学教材" /><div className="space-y-4"><label><span className="atlas-label">教材名称 *</span><input name="name" required className="atlas-input" placeholder="例如：张宇 1000 题" /></label><label><span className="atlas-label">说明</span><textarea name="description" className="min-h-20 w-full rounded-lg border border-slate-200 p-3 text-sm" /></label><button className="atlas-button-primary w-full"><Plus className="size-4" />添加教材</button></div></form><form action={createChapterAction} className="atlas-card p-5"><SectionTitle title="添加章节" /><div className="space-y-4"><label><span className="atlas-label">所属教材 *</span><select name="textbookId" required className="atlas-input"><option value="">选择教材</option>{textbooks.filter((book) => book.active).map((book) => <option key={book.id} value={book.id}>{book.name}</option>)}</select></label><label><span className="atlas-label">父章节（可选）</span><select name="parentId" className="atlas-input"><option value="">顶级章节</option>{textbooks.flatMap((book) => book.chapters.filter((chapter) => chapter.active).map((chapter) => <option key={chapter.id} value={chapter.id}>{book.name} / {chapter.name}</option>))}</select></label><label><span className="atlas-label">章节名称 *</span><input name="name" required className="atlas-input" /></label><button className="atlas-button-primary w-full"><Plus className="size-4" />添加章节</button></div></form></aside>
    </div>
  </>;
}
