import { DatabaseBackup, Download, FileArchive, FileText, ShieldCheck, UploadCloud } from 'lucide-react';
import { PageHeader, StatusPill } from '@/components/mistake-atlas/ui';

const exportOptions = [
  { name: '完整 JSON', description: '适合迁移与程序化恢复', icon: FileText },
  { name: 'Markdown + 图片 ZIP', description: '适合人工归档与阅读', icon: FileArchive },
  { name: '统计 CSV', description: '适合进一步分析', icon: Download },
];

export default function ImportsPage() {
  return <><PageHeader eyebrow="Data center" title="导入与导出" description="Markdown 是主要录入格式，JSON 用于完整备份。任何导入都必须先预览、再确认。" /><div className="grid gap-5 xl:grid-cols-2"><div className="atlas-card p-6"><div className="flex items-start justify-between"><div className="grid size-12 place-items-center rounded-xl bg-blue-50 text-blue-700"><UploadCloud className="size-6" /></div><StatusPill tone="blue">推荐</StatusPill></div><h2 className="mt-5 font-serif text-xl font-semibold text-slate-900">导入错题</h2><p className="mt-2 text-sm leading-6 text-slate-500">上传单个 Markdown、多个文件或包含图片的 ZIP 包。系统将检查字段、重复题目与危险路径。</p><button className="paper-grid mt-5 flex h-44 w-full flex-col items-center justify-center rounded-xl border border-dashed border-slate-300 text-slate-500 hover:border-blue-400 hover:text-blue-700"><FileArchive className="mb-3 size-8" /><strong className="text-sm">拖拽文件到这里</strong><span className="mt-1 text-xs text-slate-400">.md、.zip 或 .json</span></button><button className="atlas-button-primary mt-4 w-full">选择文件并生成预览</button></div><div className="atlas-card p-6"><div className="grid size-12 place-items-center rounded-xl bg-slate-100 text-slate-600"><DatabaseBackup className="size-6" /></div><h2 className="mt-5 font-serif text-xl font-semibold text-slate-900">导出与备份</h2><p className="mt-2 text-sm leading-6 text-slate-500">完整导出题目、分类、重做历史和附件索引。下载地址只在短时间内有效。</p><div className="mt-5 space-y-3">{exportOptions.map(({ name, description, icon: Icon }) => <button key={name} className="flex w-full items-center gap-3 rounded-xl border border-slate-200 p-4 text-left hover:bg-slate-50"><Icon className="size-5 text-slate-400" /><span className="flex-1"><strong className="block text-sm text-slate-800">{name}</strong><span className="text-xs text-slate-400">{description}</span></span><Download className="size-4 text-slate-400" /></button>)}</div></div></div><div className="mt-5 flex items-start gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-sm text-emerald-800"><ShieldCheck className="mt-0.5 size-5 shrink-0" /><div><strong>安全策略</strong><p className="mt-1 text-xs leading-5">ZIP 导入将限制文件数量、总大小和压缩比，并阻止路径穿越；重复题目默认不会静默覆盖。</p></div></div></>;
}
