import { BrainCircuit, ShieldCheck } from 'lucide-react';
import { AiWorkbench } from '@/components/mistake-atlas/ai-workbench';
import { PageHeader, StatusPill } from '@/components/mistake-atlas/ui';
import { prisma } from '@/lib/prisma';

export default async function AiPage() {
  const math = await prisma.subject.findUniqueOrThrow({ where: { slug: 'mathematics' } });
  const questions = await prisma.question.findMany({ where: { subjectId: math.id, status: { not: 'DELETED' } }, include: { chapter: true, knowledgePoints: { include: { knowledgePoint: true } }, errorTypes: { include: { errorType: true } }, attempts: { orderBy: { attemptedAt: 'desc' }, take: 5 } }, orderBy: [{ wrongCount: 'desc' }, { updatedAt: 'desc' }], take: 100 });
  const context = { subject: '数学', generatedAt: new Date().toISOString(), summary: { questions: questions.length, mastered: questions.filter((item) => item.status === 'MASTERED').length, repeatedErrors: questions.filter((item) => item.wrongCount >= 3).length }, questions: questions.map((item) => ({ code: item.code, title: item.title, chapter: item.chapter.name, wrongReason: item.wrongReason, reflection: item.reflection, correctStreak: item.correctStreak, wrongCount: item.wrongCount, status: item.status, knowledgePoints: item.knowledgePoints.map((entry) => entry.knowledgePoint.name), errorTypes: item.errorTypes.map((entry) => entry.errorType.name), recentAttempts: item.attempts.map((attempt) => ({ result: attempt.result, attemptedAt: attempt.attemptedAt })) })) };
  const enabled = Boolean(process.env.AI_API_KEY && process.env.AI_BASE_URL && process.env.AI_MODEL);
  return <><PageHeader eyebrow="Mathematics · AI context" title="AI 学习分析" description="AI 只能读取本次预览中明确列出的数学数据，不会直接修改错题和分类。" action={<StatusPill tone={enabled ? 'green' : 'amber'}>{enabled ? 'Provider 已配置' : '等待 Provider 配置'}</StatusPill>} /><div className="grid gap-5 2xl:grid-cols-[minmax(0,1fr)_340px]"><AiWorkbench enabled={enabled} context={context} /><aside className="space-y-5"><div className="atlas-card p-5"><div className="flex items-center gap-2 font-semibold text-slate-800"><BrainCircuit className="size-4" />本次上下文</div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div className="rounded-lg bg-slate-50 p-3"><div className="font-serif text-xl font-semibold">{context.summary.questions}</div><div className="mt-1 text-[10px] text-slate-400">错题</div></div><div className="rounded-lg bg-slate-50 p-3"><div className="font-serif text-xl font-semibold">{context.summary.mastered}</div><div className="mt-1 text-[10px] text-slate-400">掌握</div></div><div className="rounded-lg bg-slate-50 p-3"><div className="font-serif text-xl font-semibold">{context.summary.repeatedErrors}</div><div className="mt-1 text-[10px] text-slate-400">反复错误</div></div></div></div><div className="rounded-2xl border border-blue-200 bg-blue-50 p-5 text-xs leading-6 text-blue-800"><ShieldCheck className="mb-2 size-5" /><strong>安全边界</strong><br />API Key 仅保存在服务器环境变量中；发送行为会记录模型名和上下文长度，但不会把密钥写入日志。</div></aside></div></>;
}
