import { BrainCircuit, Database, Eye, ImageOff, LockKeyhole, Send } from 'lucide-react';
import { PageHeader, StatusPill } from '@/components/mistake-atlas/ui';

const contextItems = [
  { icon: Database, label: '数据范围', value: '选中的 3 道题 + 重做历史' },
  { icon: ImageOff, label: '原题图片', value: '默认不发送' },
  { icon: BrainCircuit, label: '服务商', value: 'DeepSeek / 待配置' },
  { icon: LockKeyhole, label: '响应留存', value: '仅保存元数据' },
];

export default function AiPage() {
  return <><PageHeader eyebrow="AI workspace" title="AI 学习分析" description="AI 只提供学习建议，不直接修改分类或数据库；发送前始终展示上下文范围。" /><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><div className="atlas-card p-6"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-blue-50 text-blue-700"><BrainCircuit className="size-6" /></div><div><h2 className="font-semibold text-slate-900">新建分析</h2><p className="mt-1 text-xs text-slate-400">选择目的和学习数据范围</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{['分析我的错因', '推荐错误类型', '汇总共同问题', '生成周报总结'].map((item, index) => <button key={item} className={`rounded-xl border p-4 text-left transition ${index === 0 ? 'border-blue-300 bg-blue-50' : 'border-slate-200 hover:bg-slate-50'}`}><strong className="text-sm text-slate-800">{item}</strong><p className="mt-1 text-xs leading-5 text-slate-400">{['针对选中题目找出思维断点', '基于错因推荐可配置分类', '分析一组题目的重复模式', '结合本周统计生成自然语言复盘'][index]}</p></button>)}</div><label className="mt-6 block"><span className="atlas-label">补充说明</span><textarea className="min-h-32 w-full rounded-xl border border-slate-200 p-4 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100" placeholder="例如：重点分析我为什么总在极限换元时卡住…" /></label><button className="atlas-button-primary mt-4"><Eye className="size-4" />预览将发送的数据</button></div><aside className="space-y-5"><div className="atlas-card p-6"><div className="flex items-center justify-between"><h2 className="font-semibold text-slate-900">上下文预览</h2><StatusPill tone="green">未发送</StatusPill></div><div className="mt-5 space-y-4 text-sm">{contextItems.map(({ icon: Icon, label, value }) => <div key={label} className="flex gap-3"><Icon className="mt-0.5 size-4 text-slate-400" /><div><div className="text-xs text-slate-400">{label}</div><div className="mt-1 font-medium text-slate-700">{value}</div></div></div>)}</div><button disabled className="mt-6 inline-flex h-10 w-full cursor-not-allowed items-center justify-center gap-2 rounded-lg bg-slate-200 text-sm font-semibold text-slate-400"><Send className="size-4" />配置 Provider 后发送</button></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-xs leading-6 text-amber-800"><strong>隐私提醒</strong><br />允许发送全部数据不等于默认自动发送。全量上下文和图片发送都需要二次确认并进入审计日志。</div></aside></div></>;
}
